# telegraf config mounting
apiVersion: v1
kind: Secret
metadata:
  name: keycheck-telegraf-secret
data:
  telegraf.conf: <SECRET>

---

# aws config mounting
apiVersion: v1
kind: Secret
metadata:
  name: keycheck-aws-secret
data:
  config: <SECRET>

---

# slack_id mounting
apiVersion: v1
kind: Secret
metadata:
  name: keycheck-slack-id-mapping
data:
  slack_ID_mapping.py: <SECRET>
